/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-target_i386.h"

uint16_t _TRACE_KVM_SEV_INIT_DSTATE;
uint16_t _TRACE_KVM_MEMCRYPT_REGISTER_REGION_DSTATE;
uint16_t _TRACE_KVM_MEMCRYPT_UNREGISTER_REGION_DSTATE;
uint16_t _TRACE_KVM_SEV_CHANGE_STATE_DSTATE;
uint16_t _TRACE_KVM_SEV_LAUNCH_START_DSTATE;
uint16_t _TRACE_KVM_SEV_LAUNCH_UPDATE_DATA_DSTATE;
uint16_t _TRACE_KVM_SEV_LAUNCH_MEASUREMENT_DSTATE;
uint16_t _TRACE_KVM_SEV_LAUNCH_FINISH_DSTATE;
uint16_t _TRACE_KVM_SEV_LAUNCH_SECRET_DSTATE;
uint16_t _TRACE_KVM_SEV_ATTESTATION_REPORT_DSTATE;
TraceEvent _TRACE_KVM_SEV_INIT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_init",
    .sstate = TRACE_KVM_SEV_INIT_ENABLED,
    .dstate = &_TRACE_KVM_SEV_INIT_DSTATE 
};
TraceEvent _TRACE_KVM_MEMCRYPT_REGISTER_REGION_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_memcrypt_register_region",
    .sstate = TRACE_KVM_MEMCRYPT_REGISTER_REGION_ENABLED,
    .dstate = &_TRACE_KVM_MEMCRYPT_REGISTER_REGION_DSTATE 
};
TraceEvent _TRACE_KVM_MEMCRYPT_UNREGISTER_REGION_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_memcrypt_unregister_region",
    .sstate = TRACE_KVM_MEMCRYPT_UNREGISTER_REGION_ENABLED,
    .dstate = &_TRACE_KVM_MEMCRYPT_UNREGISTER_REGION_DSTATE 
};
TraceEvent _TRACE_KVM_SEV_CHANGE_STATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_change_state",
    .sstate = TRACE_KVM_SEV_CHANGE_STATE_ENABLED,
    .dstate = &_TRACE_KVM_SEV_CHANGE_STATE_DSTATE 
};
TraceEvent _TRACE_KVM_SEV_LAUNCH_START_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_launch_start",
    .sstate = TRACE_KVM_SEV_LAUNCH_START_ENABLED,
    .dstate = &_TRACE_KVM_SEV_LAUNCH_START_DSTATE 
};
TraceEvent _TRACE_KVM_SEV_LAUNCH_UPDATE_DATA_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_launch_update_data",
    .sstate = TRACE_KVM_SEV_LAUNCH_UPDATE_DATA_ENABLED,
    .dstate = &_TRACE_KVM_SEV_LAUNCH_UPDATE_DATA_DSTATE 
};
TraceEvent _TRACE_KVM_SEV_LAUNCH_MEASUREMENT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_launch_measurement",
    .sstate = TRACE_KVM_SEV_LAUNCH_MEASUREMENT_ENABLED,
    .dstate = &_TRACE_KVM_SEV_LAUNCH_MEASUREMENT_DSTATE 
};
TraceEvent _TRACE_KVM_SEV_LAUNCH_FINISH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_launch_finish",
    .sstate = TRACE_KVM_SEV_LAUNCH_FINISH_ENABLED,
    .dstate = &_TRACE_KVM_SEV_LAUNCH_FINISH_DSTATE 
};
TraceEvent _TRACE_KVM_SEV_LAUNCH_SECRET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_launch_secret",
    .sstate = TRACE_KVM_SEV_LAUNCH_SECRET_ENABLED,
    .dstate = &_TRACE_KVM_SEV_LAUNCH_SECRET_DSTATE 
};
TraceEvent _TRACE_KVM_SEV_ATTESTATION_REPORT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "kvm_sev_attestation_report",
    .sstate = TRACE_KVM_SEV_ATTESTATION_REPORT_ENABLED,
    .dstate = &_TRACE_KVM_SEV_ATTESTATION_REPORT_DSTATE 
};
TraceEvent *target_i386_trace_events[] = {
    &_TRACE_KVM_SEV_INIT_EVENT,
    &_TRACE_KVM_MEMCRYPT_REGISTER_REGION_EVENT,
    &_TRACE_KVM_MEMCRYPT_UNREGISTER_REGION_EVENT,
    &_TRACE_KVM_SEV_CHANGE_STATE_EVENT,
    &_TRACE_KVM_SEV_LAUNCH_START_EVENT,
    &_TRACE_KVM_SEV_LAUNCH_UPDATE_DATA_EVENT,
    &_TRACE_KVM_SEV_LAUNCH_MEASUREMENT_EVENT,
    &_TRACE_KVM_SEV_LAUNCH_FINISH_EVENT,
    &_TRACE_KVM_SEV_LAUNCH_SECRET_EVENT,
    &_TRACE_KVM_SEV_ATTESTATION_REPORT_EVENT,
  NULL,
};

static void trace_target_i386_register_events(void)
{
    trace_event_register_group(target_i386_trace_events);
}
trace_init(trace_target_i386_register_events)
