/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_ACPI_GENERATED_TRACERS_H
#define TRACE_HW_ACPI_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_ADDR_LO_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_ADDR_HI_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_SIZE_LO_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_SIZE_HI_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_PXM_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_READ_FLAGS_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_WRITE_SLOT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_WRITE_OST_EV_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_WRITE_OST_STATUS_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_CLEAR_INSERT_EVT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_PC_DIMM_DELETED_EVENT;
extern TraceEvent _TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_READ_FLAGS_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_IDX_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_CMD_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_READ_CMD_DATA_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_READ_CMD_DATA2_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_EJECTING_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_FW_REMOVE_CPU_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_OST_EV_EVENT;
extern TraceEvent _TRACE_CPUHP_ACPI_WRITE_OST_STATUS_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_EJECT_SLOT_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_UNPLUG_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_UNPLUG_REQUEST_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_UP_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_DOWN_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_FEATURES_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_ACPI_INDEX_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_ACPI_INDEX_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_RMV_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_SEL_READ_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_EJ_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_PCI_SEL_WRITE_EVENT;
extern TraceEvent _TRACE_PIIX4_GPE_READB_EVENT;
extern TraceEvent _TRACE_PIIX4_GPE_WRITEB_EVENT;
extern TraceEvent _TRACE_TCO_TIMER_RELOAD_EVENT;
extern TraceEvent _TRACE_TCO_TIMER_EXPIRED_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REG_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REG_READ_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_MEM_WRITE_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_MEM_READ_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_PCI_BAR_0_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_PCI_BAR_1_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REALIZEFN_IN_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_REALIZEFN_OUT_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_RESET_IN_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_RESET_OUT_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_POST_LOAD_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_CLASS_INIT_IN_EVENT;
extern TraceEvent _TRACE_ACPI_ERST_CLASS_INIT_OUT_EVENT;
extern uint16_t _TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_ADDR_LO_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_ADDR_HI_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_SIZE_LO_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_SIZE_HI_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_PXM_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_READ_FLAGS_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_WRITE_SLOT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_WRITE_OST_EV_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_WRITE_OST_STATUS_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_CLEAR_INSERT_EVT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_PC_DIMM_DELETED_DSTATE;
extern uint16_t _TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_READ_FLAGS_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_IDX_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_CMD_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_READ_CMD_DATA_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_READ_CMD_DATA2_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_EJECTING_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_FW_REMOVE_CPU_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_OST_EV_DSTATE;
extern uint16_t _TRACE_CPUHP_ACPI_WRITE_OST_STATUS_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_EJECT_SLOT_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_UNPLUG_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_UNPLUG_REQUEST_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_UP_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_DOWN_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_FEATURES_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_ACPI_INDEX_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_ACPI_INDEX_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_RMV_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_SEL_READ_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_EJ_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_PCI_SEL_WRITE_DSTATE;
extern uint16_t _TRACE_PIIX4_GPE_READB_DSTATE;
extern uint16_t _TRACE_PIIX4_GPE_WRITEB_DSTATE;
extern uint16_t _TRACE_TCO_TIMER_RELOAD_DSTATE;
extern uint16_t _TRACE_TCO_TIMER_EXPIRED_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REG_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REG_READ_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_MEM_WRITE_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_MEM_READ_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_PCI_BAR_0_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_PCI_BAR_1_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REALIZEFN_IN_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_REALIZEFN_OUT_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_RESET_IN_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_RESET_OUT_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_POST_LOAD_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_CLASS_INIT_IN_DSTATE;
extern uint16_t _TRACE_ACPI_ERST_CLASS_INIT_OUT_DSTATE;
#define TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_ENABLED 1
#define TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_ENABLED 1
#define TRACE_MHP_ACPI_READ_ADDR_LO_ENABLED 1
#define TRACE_MHP_ACPI_READ_ADDR_HI_ENABLED 1
#define TRACE_MHP_ACPI_READ_SIZE_LO_ENABLED 1
#define TRACE_MHP_ACPI_READ_SIZE_HI_ENABLED 1
#define TRACE_MHP_ACPI_READ_PXM_ENABLED 1
#define TRACE_MHP_ACPI_READ_FLAGS_ENABLED 1
#define TRACE_MHP_ACPI_WRITE_SLOT_ENABLED 1
#define TRACE_MHP_ACPI_WRITE_OST_EV_ENABLED 1
#define TRACE_MHP_ACPI_WRITE_OST_STATUS_ENABLED 1
#define TRACE_MHP_ACPI_CLEAR_INSERT_EVT_ENABLED 1
#define TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_ENABLED 1
#define TRACE_MHP_ACPI_PC_DIMM_DELETED_ENABLED 1
#define TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_ENABLED 1
#define TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_ENABLED 1
#define TRACE_CPUHP_ACPI_READ_FLAGS_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_IDX_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_CMD_ENABLED 1
#define TRACE_CPUHP_ACPI_READ_CMD_DATA_ENABLED 1
#define TRACE_CPUHP_ACPI_READ_CMD_DATA2_ENABLED 1
#define TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_ENABLED 1
#define TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_ENABLED 1
#define TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_ENABLED 1
#define TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_EJECTING_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_FW_REMOVE_CPU_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_OST_EV_ENABLED 1
#define TRACE_CPUHP_ACPI_WRITE_OST_STATUS_ENABLED 1
#define TRACE_ACPI_PCI_EJECT_SLOT_ENABLED 1
#define TRACE_ACPI_PCI_UNPLUG_ENABLED 1
#define TRACE_ACPI_PCI_UNPLUG_REQUEST_ENABLED 1
#define TRACE_ACPI_PCI_UP_READ_ENABLED 1
#define TRACE_ACPI_PCI_DOWN_READ_ENABLED 1
#define TRACE_ACPI_PCI_FEATURES_READ_ENABLED 1
#define TRACE_ACPI_PCI_ACPI_INDEX_READ_ENABLED 1
#define TRACE_ACPI_PCI_ACPI_INDEX_WRITE_ENABLED 1
#define TRACE_ACPI_PCI_RMV_READ_ENABLED 1
#define TRACE_ACPI_PCI_SEL_READ_ENABLED 1
#define TRACE_ACPI_PCI_EJ_WRITE_ENABLED 1
#define TRACE_ACPI_PCI_SEL_WRITE_ENABLED 1
#define TRACE_PIIX4_GPE_READB_ENABLED 1
#define TRACE_PIIX4_GPE_WRITEB_ENABLED 1
#define TRACE_TCO_TIMER_RELOAD_ENABLED 1
#define TRACE_TCO_TIMER_EXPIRED_ENABLED 1
#define TRACE_ACPI_ERST_REG_WRITE_ENABLED 1
#define TRACE_ACPI_ERST_REG_READ_ENABLED 1
#define TRACE_ACPI_ERST_MEM_WRITE_ENABLED 1
#define TRACE_ACPI_ERST_MEM_READ_ENABLED 1
#define TRACE_ACPI_ERST_PCI_BAR_0_ENABLED 1
#define TRACE_ACPI_ERST_PCI_BAR_1_ENABLED 1
#define TRACE_ACPI_ERST_REALIZEFN_IN_ENABLED 1
#define TRACE_ACPI_ERST_REALIZEFN_OUT_ENABLED 1
#define TRACE_ACPI_ERST_RESET_IN_ENABLED 1
#define TRACE_ACPI_ERST_RESET_OUT_ENABLED 1
#define TRACE_ACPI_ERST_POST_LOAD_ENABLED 1
#define TRACE_ACPI_ERST_CLASS_INIT_IN_ENABLED 1
#define TRACE_ACPI_ERST_CLASS_INIT_OUT_ENABLED 1
#include "qemu/log-for-trace.h"
#include "qemu/error-report.h"


#define TRACE_MHP_ACPI_INVALID_SLOT_SELECTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_INVALID_SLOT_SELECTED) || \
    false)

static inline void _nocheck__trace_mhp_acpi_invalid_slot_selected(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_INVALID_SLOT_SELECTED) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 4 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_invalid_slot_selected " "0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot);
#line 205 "trace/trace-hw_acpi.h"
        } else {
#line 4 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_invalid_slot_selected " "0x%"PRIx32 "\n", slot);
#line 209 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_invalid_slot_selected(uint32_t slot)
{
    if (true) {
        _nocheck__trace_mhp_acpi_invalid_slot_selected(slot);
    }
}

#define TRACE_MHP_ACPI_EJECTING_INVALID_SLOT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_EJECTING_INVALID_SLOT) || \
    false)

static inline void _nocheck__trace_mhp_acpi_ejecting_invalid_slot(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_EJECTING_INVALID_SLOT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 5 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_ejecting_invalid_slot " "0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot);
#line 236 "trace/trace-hw_acpi.h"
        } else {
#line 5 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_ejecting_invalid_slot " "0x%"PRIx32 "\n", slot);
#line 240 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_ejecting_invalid_slot(uint32_t slot)
{
    if (true) {
        _nocheck__trace_mhp_acpi_ejecting_invalid_slot(slot);
    }
}

#define TRACE_MHP_ACPI_READ_ADDR_LO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_ADDR_LO) || \
    false)

static inline void _nocheck__trace_mhp_acpi_read_addr_lo(uint32_t slot, uint32_t addr)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_ADDR_LO) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 6 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_read_addr_lo " "slot[0x%"PRIx32"] addr lo: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, addr);
#line 267 "trace/trace-hw_acpi.h"
        } else {
#line 6 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_addr_lo " "slot[0x%"PRIx32"] addr lo: 0x%"PRIx32 "\n", slot, addr);
#line 271 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_read_addr_lo(uint32_t slot, uint32_t addr)
{
    if (true) {
        _nocheck__trace_mhp_acpi_read_addr_lo(slot, addr);
    }
}

#define TRACE_MHP_ACPI_READ_ADDR_HI_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_ADDR_HI) || \
    false)

static inline void _nocheck__trace_mhp_acpi_read_addr_hi(uint32_t slot, uint32_t addr)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_ADDR_HI) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 7 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_read_addr_hi " "slot[0x%"PRIx32"] addr hi: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, addr);
#line 298 "trace/trace-hw_acpi.h"
        } else {
#line 7 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_addr_hi " "slot[0x%"PRIx32"] addr hi: 0x%"PRIx32 "\n", slot, addr);
#line 302 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_read_addr_hi(uint32_t slot, uint32_t addr)
{
    if (true) {
        _nocheck__trace_mhp_acpi_read_addr_hi(slot, addr);
    }
}

#define TRACE_MHP_ACPI_READ_SIZE_LO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_SIZE_LO) || \
    false)

static inline void _nocheck__trace_mhp_acpi_read_size_lo(uint32_t slot, uint32_t size)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_SIZE_LO) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 8 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_read_size_lo " "slot[0x%"PRIx32"] size lo: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, size);
#line 329 "trace/trace-hw_acpi.h"
        } else {
#line 8 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_size_lo " "slot[0x%"PRIx32"] size lo: 0x%"PRIx32 "\n", slot, size);
#line 333 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_read_size_lo(uint32_t slot, uint32_t size)
{
    if (true) {
        _nocheck__trace_mhp_acpi_read_size_lo(slot, size);
    }
}

#define TRACE_MHP_ACPI_READ_SIZE_HI_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_SIZE_HI) || \
    false)

static inline void _nocheck__trace_mhp_acpi_read_size_hi(uint32_t slot, uint32_t size)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_SIZE_HI) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 9 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_read_size_hi " "slot[0x%"PRIx32"] size hi: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, size);
#line 360 "trace/trace-hw_acpi.h"
        } else {
#line 9 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_size_hi " "slot[0x%"PRIx32"] size hi: 0x%"PRIx32 "\n", slot, size);
#line 364 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_read_size_hi(uint32_t slot, uint32_t size)
{
    if (true) {
        _nocheck__trace_mhp_acpi_read_size_hi(slot, size);
    }
}

#define TRACE_MHP_ACPI_READ_PXM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_PXM) || \
    false)

static inline void _nocheck__trace_mhp_acpi_read_pxm(uint32_t slot, uint32_t pxm)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_PXM) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 10 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_read_pxm " "slot[0x%"PRIx32"] proximity: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, pxm);
#line 391 "trace/trace-hw_acpi.h"
        } else {
#line 10 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_pxm " "slot[0x%"PRIx32"] proximity: 0x%"PRIx32 "\n", slot, pxm);
#line 395 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_read_pxm(uint32_t slot, uint32_t pxm)
{
    if (true) {
        _nocheck__trace_mhp_acpi_read_pxm(slot, pxm);
    }
}

#define TRACE_MHP_ACPI_READ_FLAGS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_READ_FLAGS) || \
    false)

static inline void _nocheck__trace_mhp_acpi_read_flags(uint32_t slot, uint32_t flags)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_READ_FLAGS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 11 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_read_flags " "slot[0x%"PRIx32"] flags: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, flags);
#line 422 "trace/trace-hw_acpi.h"
        } else {
#line 11 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_read_flags " "slot[0x%"PRIx32"] flags: 0x%"PRIx32 "\n", slot, flags);
#line 426 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_read_flags(uint32_t slot, uint32_t flags)
{
    if (true) {
        _nocheck__trace_mhp_acpi_read_flags(slot, flags);
    }
}

#define TRACE_MHP_ACPI_WRITE_SLOT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_WRITE_SLOT) || \
    false)

static inline void _nocheck__trace_mhp_acpi_write_slot(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_WRITE_SLOT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 12 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_write_slot " "set active slot: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot);
#line 453 "trace/trace-hw_acpi.h"
        } else {
#line 12 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_write_slot " "set active slot: 0x%"PRIx32 "\n", slot);
#line 457 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_write_slot(uint32_t slot)
{
    if (true) {
        _nocheck__trace_mhp_acpi_write_slot(slot);
    }
}

#define TRACE_MHP_ACPI_WRITE_OST_EV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_WRITE_OST_EV) || \
    false)

static inline void _nocheck__trace_mhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_WRITE_OST_EV) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 13 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_write_ost_ev " "slot[0x%"PRIx32"] OST EVENT: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, ev);
#line 484 "trace/trace-hw_acpi.h"
        } else {
#line 13 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_write_ost_ev " "slot[0x%"PRIx32"] OST EVENT: 0x%"PRIx32 "\n", slot, ev);
#line 488 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev)
{
    if (true) {
        _nocheck__trace_mhp_acpi_write_ost_ev(slot, ev);
    }
}

#define TRACE_MHP_ACPI_WRITE_OST_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_WRITE_OST_STATUS) || \
    false)

static inline void _nocheck__trace_mhp_acpi_write_ost_status(uint32_t slot, uint32_t st)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_WRITE_OST_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 14 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_write_ost_status " "slot[0x%"PRIx32"] OST STATUS: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, st);
#line 515 "trace/trace-hw_acpi.h"
        } else {
#line 14 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_write_ost_status " "slot[0x%"PRIx32"] OST STATUS: 0x%"PRIx32 "\n", slot, st);
#line 519 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_write_ost_status(uint32_t slot, uint32_t st)
{
    if (true) {
        _nocheck__trace_mhp_acpi_write_ost_status(slot, st);
    }
}

#define TRACE_MHP_ACPI_CLEAR_INSERT_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_CLEAR_INSERT_EVT) || \
    false)

static inline void _nocheck__trace_mhp_acpi_clear_insert_evt(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_CLEAR_INSERT_EVT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 15 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_clear_insert_evt " "slot[0x%"PRIx32"] clear insert event" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot);
#line 546 "trace/trace-hw_acpi.h"
        } else {
#line 15 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_clear_insert_evt " "slot[0x%"PRIx32"] clear insert event" "\n", slot);
#line 550 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_clear_insert_evt(uint32_t slot)
{
    if (true) {
        _nocheck__trace_mhp_acpi_clear_insert_evt(slot);
    }
}

#define TRACE_MHP_ACPI_CLEAR_REMOVE_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_CLEAR_REMOVE_EVT) || \
    false)

static inline void _nocheck__trace_mhp_acpi_clear_remove_evt(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_CLEAR_REMOVE_EVT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 16 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_clear_remove_evt " "slot[0x%"PRIx32"] clear remove event" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot);
#line 577 "trace/trace-hw_acpi.h"
        } else {
#line 16 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_clear_remove_evt " "slot[0x%"PRIx32"] clear remove event" "\n", slot);
#line 581 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_clear_remove_evt(uint32_t slot)
{
    if (true) {
        _nocheck__trace_mhp_acpi_clear_remove_evt(slot);
    }
}

#define TRACE_MHP_ACPI_PC_DIMM_DELETED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_PC_DIMM_DELETED) || \
    false)

static inline void _nocheck__trace_mhp_acpi_pc_dimm_deleted(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_PC_DIMM_DELETED) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 17 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_pc_dimm_deleted " "slot[0x%"PRIx32"] pc-dimm deleted" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot);
#line 608 "trace/trace-hw_acpi.h"
        } else {
#line 17 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_pc_dimm_deleted " "slot[0x%"PRIx32"] pc-dimm deleted" "\n", slot);
#line 612 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_pc_dimm_deleted(uint32_t slot)
{
    if (true) {
        _nocheck__trace_mhp_acpi_pc_dimm_deleted(slot);
    }
}

#define TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED) || \
    false)

static inline void _nocheck__trace_mhp_acpi_pc_dimm_delete_failed(uint32_t slot)
{
    if (trace_event_get_state(TRACE_MHP_ACPI_PC_DIMM_DELETE_FAILED) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 18 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:mhp_acpi_pc_dimm_delete_failed " "slot[0x%"PRIx32"] pc-dimm delete failed" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot);
#line 639 "trace/trace-hw_acpi.h"
        } else {
#line 18 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("mhp_acpi_pc_dimm_delete_failed " "slot[0x%"PRIx32"] pc-dimm delete failed" "\n", slot);
#line 643 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_mhp_acpi_pc_dimm_delete_failed(uint32_t slot)
{
    if (true) {
        _nocheck__trace_mhp_acpi_pc_dimm_delete_failed(slot);
    }
}

#define TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_invalid_idx_selected(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_INVALID_IDX_SELECTED) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 21 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_invalid_idx_selected " "0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 670 "trace/trace-hw_acpi.h"
        } else {
#line 21 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_invalid_idx_selected " "0x%"PRIx32 "\n", idx);
#line 674 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_invalid_idx_selected(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_invalid_idx_selected(idx);
    }
}

#define TRACE_CPUHP_ACPI_READ_FLAGS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_READ_FLAGS) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_read_flags(uint32_t idx, uint8_t flags)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_READ_FLAGS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 22 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_read_flags " "idx[0x%"PRIx32"] flags: 0x%"PRIx8 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx, flags);
#line 701 "trace/trace-hw_acpi.h"
        } else {
#line 22 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_read_flags " "idx[0x%"PRIx32"] flags: 0x%"PRIx8 "\n", idx, flags);
#line 705 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_read_flags(uint32_t idx, uint8_t flags)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_read_flags(idx, flags);
    }
}

#define TRACE_CPUHP_ACPI_WRITE_IDX_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_IDX) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_write_idx(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_IDX) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 23 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_write_idx " "set active cpu idx: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 732 "trace/trace-hw_acpi.h"
        } else {
#line 23 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_idx " "set active cpu idx: 0x%"PRIx32 "\n", idx);
#line 736 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_write_idx(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_write_idx(idx);
    }
}

#define TRACE_CPUHP_ACPI_WRITE_CMD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_CMD) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_write_cmd(uint32_t idx, uint8_t cmd)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_CMD) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 24 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_write_cmd " "idx[0x%"PRIx32"] cmd: 0x%"PRIx8 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx, cmd);
#line 763 "trace/trace-hw_acpi.h"
        } else {
#line 24 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_cmd " "idx[0x%"PRIx32"] cmd: 0x%"PRIx8 "\n", idx, cmd);
#line 767 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_write_cmd(uint32_t idx, uint8_t cmd)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_write_cmd(idx, cmd);
    }
}

#define TRACE_CPUHP_ACPI_READ_CMD_DATA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_READ_CMD_DATA) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_read_cmd_data(uint32_t idx, uint32_t data)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_READ_CMD_DATA) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 25 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_read_cmd_data " "idx[0x%"PRIx32"] data: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx, data);
#line 794 "trace/trace-hw_acpi.h"
        } else {
#line 25 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_read_cmd_data " "idx[0x%"PRIx32"] data: 0x%"PRIx32 "\n", idx, data);
#line 798 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_read_cmd_data(uint32_t idx, uint32_t data)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_read_cmd_data(idx, data);
    }
}

#define TRACE_CPUHP_ACPI_READ_CMD_DATA2_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_READ_CMD_DATA2) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_read_cmd_data2(uint32_t idx, uint32_t data)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_READ_CMD_DATA2) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 26 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_read_cmd_data2 " "idx[0x%"PRIx32"] data: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx, data);
#line 825 "trace/trace-hw_acpi.h"
        } else {
#line 26 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_read_cmd_data2 " "idx[0x%"PRIx32"] data: 0x%"PRIx32 "\n", idx, data);
#line 829 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_read_cmd_data2(uint32_t idx, uint32_t data)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_read_cmd_data2(idx, data);
    }
}

#define TRACE_CPUHP_ACPI_CPU_HAS_EVENTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_CPU_HAS_EVENTS) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_cpu_has_events(uint32_t idx, bool ins, bool rm)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_CPU_HAS_EVENTS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 27 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_cpu_has_events " "idx[0x%"PRIx32"] inserting: %d, removing: %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx, ins, rm);
#line 856 "trace/trace-hw_acpi.h"
        } else {
#line 27 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_cpu_has_events " "idx[0x%"PRIx32"] inserting: %d, removing: %d" "\n", idx, ins, rm);
#line 860 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_cpu_has_events(uint32_t idx, bool ins, bool rm)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_cpu_has_events(idx, ins, rm);
    }
}

#define TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_clear_inserting_evt(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_CLEAR_INSERTING_EVT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 28 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_clear_inserting_evt " "idx[0x%"PRIx32"]" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 887 "trace/trace-hw_acpi.h"
        } else {
#line 28 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_clear_inserting_evt " "idx[0x%"PRIx32"]" "\n", idx);
#line 891 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_clear_inserting_evt(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_clear_inserting_evt(idx);
    }
}

#define TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_clear_remove_evt(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_CLEAR_REMOVE_EVT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 29 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_clear_remove_evt " "idx[0x%"PRIx32"]" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 918 "trace/trace-hw_acpi.h"
        } else {
#line 29 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_clear_remove_evt " "idx[0x%"PRIx32"]" "\n", idx);
#line 922 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_clear_remove_evt(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_clear_remove_evt(idx);
    }
}

#define TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_ejecting_invalid_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_EJECTING_INVALID_CPU) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 30 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_ejecting_invalid_cpu " "0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 949 "trace/trace-hw_acpi.h"
        } else {
#line 30 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_ejecting_invalid_cpu " "0x%"PRIx32 "\n", idx);
#line 953 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_ejecting_invalid_cpu(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_ejecting_invalid_cpu(idx);
    }
}

#define TRACE_CPUHP_ACPI_EJECTING_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_EJECTING_CPU) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_ejecting_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_EJECTING_CPU) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 31 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_ejecting_cpu " "0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 980 "trace/trace-hw_acpi.h"
        } else {
#line 31 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_ejecting_cpu " "0x%"PRIx32 "\n", idx);
#line 984 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_ejecting_cpu(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_ejecting_cpu(idx);
    }
}

#define TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_fw_remove_invalid_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_FW_REMOVE_INVALID_CPU) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 32 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_fw_remove_invalid_cpu " "0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 1011 "trace/trace-hw_acpi.h"
        } else {
#line 32 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_fw_remove_invalid_cpu " "0x%"PRIx32 "\n", idx);
#line 1015 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_fw_remove_invalid_cpu(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_fw_remove_invalid_cpu(idx);
    }
}

#define TRACE_CPUHP_ACPI_FW_REMOVE_CPU_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_FW_REMOVE_CPU) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_fw_remove_cpu(uint32_t idx)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_FW_REMOVE_CPU) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 33 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_fw_remove_cpu " "0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , idx);
#line 1042 "trace/trace-hw_acpi.h"
        } else {
#line 33 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_fw_remove_cpu " "0x%"PRIx32 "\n", idx);
#line 1046 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_fw_remove_cpu(uint32_t idx)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_fw_remove_cpu(idx);
    }
}

#define TRACE_CPUHP_ACPI_WRITE_OST_EV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_OST_EV) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_OST_EV) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 34 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_write_ost_ev " "idx[0x%"PRIx32"] OST EVENT: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, ev);
#line 1073 "trace/trace-hw_acpi.h"
        } else {
#line 34 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_ost_ev " "idx[0x%"PRIx32"] OST EVENT: 0x%"PRIx32 "\n", slot, ev);
#line 1077 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_write_ost_ev(uint32_t slot, uint32_t ev)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_write_ost_ev(slot, ev);
    }
}

#define TRACE_CPUHP_ACPI_WRITE_OST_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_CPUHP_ACPI_WRITE_OST_STATUS) || \
    false)

static inline void _nocheck__trace_cpuhp_acpi_write_ost_status(uint32_t slot, uint32_t st)
{
    if (trace_event_get_state(TRACE_CPUHP_ACPI_WRITE_OST_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 35 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:cpuhp_acpi_write_ost_status " "idx[0x%"PRIx32"] OST STATUS: 0x%"PRIx32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , slot, st);
#line 1104 "trace/trace-hw_acpi.h"
        } else {
#line 35 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("cpuhp_acpi_write_ost_status " "idx[0x%"PRIx32"] OST STATUS: 0x%"PRIx32 "\n", slot, st);
#line 1108 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_cpuhp_acpi_write_ost_status(uint32_t slot, uint32_t st)
{
    if (true) {
        _nocheck__trace_cpuhp_acpi_write_ost_status(slot, st);
    }
}

#define TRACE_ACPI_PCI_EJECT_SLOT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_EJECT_SLOT) || \
    false)

static inline void _nocheck__trace_acpi_pci_eject_slot(unsigned bsel, unsigned slot)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_EJECT_SLOT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 38 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_eject_slot " "bsel: %u slot: %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , bsel, slot);
#line 1135 "trace/trace-hw_acpi.h"
        } else {
#line 38 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_eject_slot " "bsel: %u slot: %u" "\n", bsel, slot);
#line 1139 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_eject_slot(unsigned bsel, unsigned slot)
{
    if (true) {
        _nocheck__trace_acpi_pci_eject_slot(bsel, slot);
    }
}

#define TRACE_ACPI_PCI_UNPLUG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_UNPLUG) || \
    false)

static inline void _nocheck__trace_acpi_pci_unplug(int bsel, int slot)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_UNPLUG) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 39 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_unplug " "bsel: %d slot: %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , bsel, slot);
#line 1166 "trace/trace-hw_acpi.h"
        } else {
#line 39 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_unplug " "bsel: %d slot: %d" "\n", bsel, slot);
#line 1170 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_unplug(int bsel, int slot)
{
    if (true) {
        _nocheck__trace_acpi_pci_unplug(bsel, slot);
    }
}

#define TRACE_ACPI_PCI_UNPLUG_REQUEST_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_UNPLUG_REQUEST) || \
    false)

static inline void _nocheck__trace_acpi_pci_unplug_request(int bsel, int slot)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_UNPLUG_REQUEST) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 40 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_unplug_request " "bsel: %d slot: %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , bsel, slot);
#line 1197 "trace/trace-hw_acpi.h"
        } else {
#line 40 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_unplug_request " "bsel: %d slot: %d" "\n", bsel, slot);
#line 1201 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_unplug_request(int bsel, int slot)
{
    if (true) {
        _nocheck__trace_acpi_pci_unplug_request(bsel, slot);
    }
}

#define TRACE_ACPI_PCI_UP_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_UP_READ) || \
    false)

static inline void _nocheck__trace_acpi_pci_up_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_UP_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 41 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_up_read " "%" PRIu32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , val);
#line 1228 "trace/trace-hw_acpi.h"
        } else {
#line 41 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_up_read " "%" PRIu32 "\n", val);
#line 1232 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_up_read(uint32_t val)
{
    if (true) {
        _nocheck__trace_acpi_pci_up_read(val);
    }
}

#define TRACE_ACPI_PCI_DOWN_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_DOWN_READ) || \
    false)

static inline void _nocheck__trace_acpi_pci_down_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_DOWN_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 42 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_down_read " "%" PRIu32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , val);
#line 1259 "trace/trace-hw_acpi.h"
        } else {
#line 42 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_down_read " "%" PRIu32 "\n", val);
#line 1263 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_down_read(uint32_t val)
{
    if (true) {
        _nocheck__trace_acpi_pci_down_read(val);
    }
}

#define TRACE_ACPI_PCI_FEATURES_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_FEATURES_READ) || \
    false)

static inline void _nocheck__trace_acpi_pci_features_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_FEATURES_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 43 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_features_read " "%" PRIu32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , val);
#line 1290 "trace/trace-hw_acpi.h"
        } else {
#line 43 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_features_read " "%" PRIu32 "\n", val);
#line 1294 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_features_read(uint32_t val)
{
    if (true) {
        _nocheck__trace_acpi_pci_features_read(val);
    }
}

#define TRACE_ACPI_PCI_ACPI_INDEX_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_ACPI_INDEX_READ) || \
    false)

static inline void _nocheck__trace_acpi_pci_acpi_index_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_ACPI_INDEX_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 44 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_acpi_index_read " "%" PRIu32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , val);
#line 1321 "trace/trace-hw_acpi.h"
        } else {
#line 44 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_acpi_index_read " "%" PRIu32 "\n", val);
#line 1325 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_acpi_index_read(uint32_t val)
{
    if (true) {
        _nocheck__trace_acpi_pci_acpi_index_read(val);
    }
}

#define TRACE_ACPI_PCI_ACPI_INDEX_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_ACPI_INDEX_WRITE) || \
    false)

static inline void _nocheck__trace_acpi_pci_acpi_index_write(unsigned bsel, unsigned slot, uint32_t aidx)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_ACPI_INDEX_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 45 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_acpi_index_write " "bsel: %u slot: %u aidx: %" PRIu32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , bsel, slot, aidx);
#line 1352 "trace/trace-hw_acpi.h"
        } else {
#line 45 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_acpi_index_write " "bsel: %u slot: %u aidx: %" PRIu32 "\n", bsel, slot, aidx);
#line 1356 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_acpi_index_write(unsigned bsel, unsigned slot, uint32_t aidx)
{
    if (true) {
        _nocheck__trace_acpi_pci_acpi_index_write(bsel, slot, aidx);
    }
}

#define TRACE_ACPI_PCI_RMV_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_RMV_READ) || \
    false)

static inline void _nocheck__trace_acpi_pci_rmv_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_RMV_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 46 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_rmv_read " "%" PRIu32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , val);
#line 1383 "trace/trace-hw_acpi.h"
        } else {
#line 46 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_rmv_read " "%" PRIu32 "\n", val);
#line 1387 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_rmv_read(uint32_t val)
{
    if (true) {
        _nocheck__trace_acpi_pci_rmv_read(val);
    }
}

#define TRACE_ACPI_PCI_SEL_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_SEL_READ) || \
    false)

static inline void _nocheck__trace_acpi_pci_sel_read(uint32_t val)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_SEL_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 47 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_sel_read " "%" PRIu32 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , val);
#line 1414 "trace/trace-hw_acpi.h"
        } else {
#line 47 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_sel_read " "%" PRIu32 "\n", val);
#line 1418 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_sel_read(uint32_t val)
{
    if (true) {
        _nocheck__trace_acpi_pci_sel_read(val);
    }
}

#define TRACE_ACPI_PCI_EJ_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_EJ_WRITE) || \
    false)

static inline void _nocheck__trace_acpi_pci_ej_write(uint64_t addr, uint64_t data)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_EJ_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 48 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_ej_write " "0x%" PRIx64 " <== %" PRIu64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, data);
#line 1445 "trace/trace-hw_acpi.h"
        } else {
#line 48 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_ej_write " "0x%" PRIx64 " <== %" PRIu64 "\n", addr, data);
#line 1449 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_ej_write(uint64_t addr, uint64_t data)
{
    if (true) {
        _nocheck__trace_acpi_pci_ej_write(addr, data);
    }
}

#define TRACE_ACPI_PCI_SEL_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_PCI_SEL_WRITE) || \
    false)

static inline void _nocheck__trace_acpi_pci_sel_write(uint64_t addr, uint64_t data)
{
    if (trace_event_get_state(TRACE_ACPI_PCI_SEL_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 49 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_pci_sel_write " "0x%" PRIx64 " <== %" PRIu64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, data);
#line 1476 "trace/trace-hw_acpi.h"
        } else {
#line 49 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_pci_sel_write " "0x%" PRIx64 " <== %" PRIu64 "\n", addr, data);
#line 1480 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_pci_sel_write(uint64_t addr, uint64_t data)
{
    if (true) {
        _nocheck__trace_acpi_pci_sel_write(addr, data);
    }
}

#define TRACE_PIIX4_GPE_READB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PIIX4_GPE_READB) || \
    false)

static inline void _nocheck__trace_piix4_gpe_readb(uint64_t addr, unsigned width, uint64_t val)
{
    if (trace_event_get_state(TRACE_PIIX4_GPE_READB) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 52 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:piix4_gpe_readb " "addr: 0x%" PRIx64 " width: %d ==> 0x%" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, width, val);
#line 1507 "trace/trace-hw_acpi.h"
        } else {
#line 52 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("piix4_gpe_readb " "addr: 0x%" PRIx64 " width: %d ==> 0x%" PRIx64 "\n", addr, width, val);
#line 1511 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_piix4_gpe_readb(uint64_t addr, unsigned width, uint64_t val)
{
    if (true) {
        _nocheck__trace_piix4_gpe_readb(addr, width, val);
    }
}

#define TRACE_PIIX4_GPE_WRITEB_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_PIIX4_GPE_WRITEB) || \
    false)

static inline void _nocheck__trace_piix4_gpe_writeb(uint64_t addr, unsigned width, uint64_t val)
{
    if (trace_event_get_state(TRACE_PIIX4_GPE_WRITEB) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 53 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:piix4_gpe_writeb " "addr: 0x%" PRIx64 " width: %d <== 0x%" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, width, val);
#line 1538 "trace/trace-hw_acpi.h"
        } else {
#line 53 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("piix4_gpe_writeb " "addr: 0x%" PRIx64 " width: %d <== 0x%" PRIx64 "\n", addr, width, val);
#line 1542 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_piix4_gpe_writeb(uint64_t addr, unsigned width, uint64_t val)
{
    if (true) {
        _nocheck__trace_piix4_gpe_writeb(addr, width, val);
    }
}

#define TRACE_TCO_TIMER_RELOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TCO_TIMER_RELOAD) || \
    false)

static inline void _nocheck__trace_tco_timer_reload(int ticks, int msec)
{
    if (trace_event_get_state(TRACE_TCO_TIMER_RELOAD) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 56 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:tco_timer_reload " "ticks=%d (%d ms)" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , ticks, msec);
#line 1569 "trace/trace-hw_acpi.h"
        } else {
#line 56 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("tco_timer_reload " "ticks=%d (%d ms)" "\n", ticks, msec);
#line 1573 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_tco_timer_reload(int ticks, int msec)
{
    if (true) {
        _nocheck__trace_tco_timer_reload(ticks, msec);
    }
}

#define TRACE_TCO_TIMER_EXPIRED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_TCO_TIMER_EXPIRED) || \
    false)

static inline void _nocheck__trace_tco_timer_expired(int timeouts_no, bool strap, bool no_reboot)
{
    if (trace_event_get_state(TRACE_TCO_TIMER_EXPIRED) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 57 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:tco_timer_expired " "timeouts_no=%d no_reboot=%d/%d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , timeouts_no, strap, no_reboot);
#line 1600 "trace/trace-hw_acpi.h"
        } else {
#line 57 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("tco_timer_expired " "timeouts_no=%d no_reboot=%d/%d" "\n", timeouts_no, strap, no_reboot);
#line 1604 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_tco_timer_expired(int timeouts_no, bool strap, bool no_reboot)
{
    if (true) {
        _nocheck__trace_tco_timer_expired(timeouts_no, strap, no_reboot);
    }
}

#define TRACE_ACPI_ERST_REG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REG_WRITE) || \
    false)

static inline void _nocheck__trace_acpi_erst_reg_write(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REG_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 60 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_reg_write " "addr: 0x%04" PRIx64 " <== 0x%016" PRIx64 " (size: %u)" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, val, size);
#line 1631 "trace/trace-hw_acpi.h"
        } else {
#line 60 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_reg_write " "addr: 0x%04" PRIx64 " <== 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 1635 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_reg_write(uint64_t addr, uint64_t val, unsigned size)
{
    if (true) {
        _nocheck__trace_acpi_erst_reg_write(addr, val, size);
    }
}

#define TRACE_ACPI_ERST_REG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REG_READ) || \
    false)

static inline void _nocheck__trace_acpi_erst_reg_read(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REG_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 61 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_reg_read " " addr: 0x%04" PRIx64 " ==> 0x%016" PRIx64 " (size: %u)" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, val, size);
#line 1662 "trace/trace-hw_acpi.h"
        } else {
#line 61 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_reg_read " " addr: 0x%04" PRIx64 " ==> 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 1666 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_reg_read(uint64_t addr, uint64_t val, unsigned size)
{
    if (true) {
        _nocheck__trace_acpi_erst_reg_read(addr, val, size);
    }
}

#define TRACE_ACPI_ERST_MEM_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_MEM_WRITE) || \
    false)

static inline void _nocheck__trace_acpi_erst_mem_write(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_MEM_WRITE) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 62 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_mem_write " "addr: 0x%06" PRIx64 " <== 0x%016" PRIx64 " (size: %u)" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, val, size);
#line 1693 "trace/trace-hw_acpi.h"
        } else {
#line 62 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_mem_write " "addr: 0x%06" PRIx64 " <== 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 1697 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_mem_write(uint64_t addr, uint64_t val, unsigned size)
{
    if (true) {
        _nocheck__trace_acpi_erst_mem_write(addr, val, size);
    }
}

#define TRACE_ACPI_ERST_MEM_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_MEM_READ) || \
    false)

static inline void _nocheck__trace_acpi_erst_mem_read(uint64_t addr, uint64_t val, unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_MEM_READ) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 63 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_mem_read " " addr: 0x%06" PRIx64 " ==> 0x%016" PRIx64 " (size: %u)" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr, val, size);
#line 1724 "trace/trace-hw_acpi.h"
        } else {
#line 63 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_mem_read " " addr: 0x%06" PRIx64 " ==> 0x%016" PRIx64 " (size: %u)" "\n", addr, val, size);
#line 1728 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_mem_read(uint64_t addr, uint64_t val, unsigned size)
{
    if (true) {
        _nocheck__trace_acpi_erst_mem_read(addr, val, size);
    }
}

#define TRACE_ACPI_ERST_PCI_BAR_0_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_PCI_BAR_0) || \
    false)

static inline void _nocheck__trace_acpi_erst_pci_bar_0(uint64_t addr)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_PCI_BAR_0) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 64 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_pci_bar_0 " "BAR0: 0x%016" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr);
#line 1755 "trace/trace-hw_acpi.h"
        } else {
#line 64 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_pci_bar_0 " "BAR0: 0x%016" PRIx64 "\n", addr);
#line 1759 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_pci_bar_0(uint64_t addr)
{
    if (true) {
        _nocheck__trace_acpi_erst_pci_bar_0(addr);
    }
}

#define TRACE_ACPI_ERST_PCI_BAR_1_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_PCI_BAR_1) || \
    false)

static inline void _nocheck__trace_acpi_erst_pci_bar_1(uint64_t addr)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_PCI_BAR_1) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 65 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_pci_bar_1 " "BAR1: 0x%016" PRIx64 "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , addr);
#line 1786 "trace/trace-hw_acpi.h"
        } else {
#line 65 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_pci_bar_1 " "BAR1: 0x%016" PRIx64 "\n", addr);
#line 1790 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_pci_bar_1(uint64_t addr)
{
    if (true) {
        _nocheck__trace_acpi_erst_pci_bar_1(addr);
    }
}

#define TRACE_ACPI_ERST_REALIZEFN_IN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REALIZEFN_IN) || \
    false)

static inline void _nocheck__trace_acpi_erst_realizefn_in(void)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REALIZEFN_IN) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 66 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_realizefn_in "  "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     );
#line 1817 "trace/trace-hw_acpi.h"
        } else {
#line 66 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_realizefn_in "  "\n");
#line 1821 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_realizefn_in(void)
{
    if (true) {
        _nocheck__trace_acpi_erst_realizefn_in();
    }
}

#define TRACE_ACPI_ERST_REALIZEFN_OUT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_REALIZEFN_OUT) || \
    false)

static inline void _nocheck__trace_acpi_erst_realizefn_out(unsigned size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_REALIZEFN_OUT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 67 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_realizefn_out " "total nvram size %u bytes" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , size);
#line 1848 "trace/trace-hw_acpi.h"
        } else {
#line 67 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_realizefn_out " "total nvram size %u bytes" "\n", size);
#line 1852 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_realizefn_out(unsigned size)
{
    if (true) {
        _nocheck__trace_acpi_erst_realizefn_out(size);
    }
}

#define TRACE_ACPI_ERST_RESET_IN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_RESET_IN) || \
    false)

static inline void _nocheck__trace_acpi_erst_reset_in(unsigned record_count)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_RESET_IN) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 68 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_reset_in " "record_count %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , record_count);
#line 1879 "trace/trace-hw_acpi.h"
        } else {
#line 68 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_reset_in " "record_count %u" "\n", record_count);
#line 1883 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_reset_in(unsigned record_count)
{
    if (true) {
        _nocheck__trace_acpi_erst_reset_in(record_count);
    }
}

#define TRACE_ACPI_ERST_RESET_OUT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_RESET_OUT) || \
    false)

static inline void _nocheck__trace_acpi_erst_reset_out(unsigned record_count)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_RESET_OUT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 69 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_reset_out " "record_count %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , record_count);
#line 1910 "trace/trace-hw_acpi.h"
        } else {
#line 69 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_reset_out " "record_count %u" "\n", record_count);
#line 1914 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_reset_out(unsigned record_count)
{
    if (true) {
        _nocheck__trace_acpi_erst_reset_out(record_count);
    }
}

#define TRACE_ACPI_ERST_POST_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_POST_LOAD) || \
    false)

static inline void _nocheck__trace_acpi_erst_post_load(void * header, unsigned slot_size)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_POST_LOAD) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 70 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_post_load " "header: 0x%p slot_size %u" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , header, slot_size);
#line 1941 "trace/trace-hw_acpi.h"
        } else {
#line 70 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_post_load " "header: 0x%p slot_size %u" "\n", header, slot_size);
#line 1945 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_post_load(void * header, unsigned slot_size)
{
    if (true) {
        _nocheck__trace_acpi_erst_post_load(header, slot_size);
    }
}

#define TRACE_ACPI_ERST_CLASS_INIT_IN_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_CLASS_INIT_IN) || \
    false)

static inline void _nocheck__trace_acpi_erst_class_init_in(void)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_CLASS_INIT_IN) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 71 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_class_init_in "  "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     );
#line 1972 "trace/trace-hw_acpi.h"
        } else {
#line 71 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_class_init_in "  "\n");
#line 1976 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_class_init_in(void)
{
    if (true) {
        _nocheck__trace_acpi_erst_class_init_in();
    }
}

#define TRACE_ACPI_ERST_CLASS_INIT_OUT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_ACPI_ERST_CLASS_INIT_OUT) || \
    false)

static inline void _nocheck__trace_acpi_erst_class_init_out(void)
{
    if (trace_event_get_state(TRACE_ACPI_ERST_CLASS_INIT_OUT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 72 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("%d@%zu.%06zu:acpi_erst_class_init_out "  "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     );
#line 2003 "trace/trace-hw_acpi.h"
        } else {
#line 72 "/home/inhoinno/FEMU/hw/acpi/trace-events"
            qemu_log("acpi_erst_class_init_out "  "\n");
#line 2007 "trace/trace-hw_acpi.h"
        }
    }
}

static inline void trace_acpi_erst_class_init_out(void)
{
    if (true) {
        _nocheck__trace_acpi_erst_class_init_out();
    }
}
#endif /* TRACE_HW_ACPI_GENERATED_TRACERS_H */
