/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-qapi_commands_qdev_trace_events.h"

uint16_t _TRACE_QMP_ENTER_DEVICE_LIST_PROPERTIES_DSTATE;
uint16_t _TRACE_QMP_EXIT_DEVICE_LIST_PROPERTIES_DSTATE;
uint16_t _TRACE_QMP_ENTER_DEVICE_DEL_DSTATE;
uint16_t _TRACE_QMP_EXIT_DEVICE_DEL_DSTATE;
TraceEvent _TRACE_QMP_ENTER_DEVICE_LIST_PROPERTIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_device_list_properties",
    .sstate = TRACE_QMP_ENTER_DEVICE_LIST_PROPERTIES_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_DEVICE_LIST_PROPERTIES_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_DEVICE_LIST_PROPERTIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_device_list_properties",
    .sstate = TRACE_QMP_EXIT_DEVICE_LIST_PROPERTIES_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_DEVICE_LIST_PROPERTIES_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_DEVICE_DEL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_device_del",
    .sstate = TRACE_QMP_ENTER_DEVICE_DEL_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_DEVICE_DEL_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_DEVICE_DEL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_device_del",
    .sstate = TRACE_QMP_EXIT_DEVICE_DEL_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_DEVICE_DEL_DSTATE 
};
TraceEvent *qapi_commands_qdev_trace_events_trace_events[] = {
    &_TRACE_QMP_ENTER_DEVICE_LIST_PROPERTIES_EVENT,
    &_TRACE_QMP_EXIT_DEVICE_LIST_PROPERTIES_EVENT,
    &_TRACE_QMP_ENTER_DEVICE_DEL_EVENT,
    &_TRACE_QMP_EXIT_DEVICE_DEL_EVENT,
  NULL,
};

static void trace_qapi_commands_qdev_trace_events_register_events(void)
{
    trace_event_register_group(qapi_commands_qdev_trace_events_trace_events);
}
trace_init(trace_qapi_commands_qdev_trace_events_register_events)
