/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-ebpf.h"

uint16_t _TRACE_EBPF_ERROR_DSTATE;
TraceEvent _TRACE_EBPF_ERROR_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "ebpf_error",
    .sstate = TRACE_EBPF_ERROR_ENABLED,
    .dstate = &_TRACE_EBPF_ERROR_DSTATE 
};
TraceEvent *ebpf_trace_events[] = {
    &_TRACE_EBPF_ERROR_EVENT,
  NULL,
};

static void trace_ebpf_register_events(void)
{
    trace_event_register_group(ebpf_trace_events);
}
trace_init(trace_ebpf_register_events)
