/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_QAPI_COMMANDS_ROCKER_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_ROCKER_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_EVENT;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE;
#define TRACE_QMP_ENTER_QUERY_ROCKER_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_ENABLED 1
#include "qemu/log-for-trace.h"
#include "qemu/error-report.h"


#define TRACE_QMP_ENTER_QUERY_ROCKER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_rocker(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 3 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_query_rocker " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 52 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 3 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker " "%s" "\n", json);
#line 56 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_query_rocker(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_rocker(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_rocker(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 4 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_query_rocker " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 83 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 4 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker " "%s %d" "\n", result, succeeded);
#line 87 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_query_rocker(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_rocker(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER_PORTS) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_rocker_ports(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER_PORTS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 5 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_query_rocker_ports " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 114 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 5 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker_ports " "%s" "\n", json);
#line 118 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_query_rocker_ports(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_rocker_ports(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER_PORTS) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_rocker_ports(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER_PORTS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 6 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_query_rocker_ports " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 145 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 6 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker_ports " "%s %d" "\n", result, succeeded);
#line 149 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_query_rocker_ports(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_rocker_ports(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_rocker_of_dpa_flows(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 7 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_query_rocker_of_dpa_flows " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 176 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 7 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker_of_dpa_flows " "%s" "\n", json);
#line 180 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_query_rocker_of_dpa_flows(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_rocker_of_dpa_flows(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_rocker_of_dpa_flows(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 8 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_query_rocker_of_dpa_flows " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 207 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 8 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker_of_dpa_flows " "%s %d" "\n", result, succeeded);
#line 211 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_query_rocker_of_dpa_flows(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_rocker_of_dpa_flows(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_rocker_of_dpa_groups(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 9 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_query_rocker_of_dpa_groups " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 238 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 9 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_enter_query_rocker_of_dpa_groups " "%s" "\n", json);
#line 242 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_query_rocker_of_dpa_groups(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_rocker_of_dpa_groups(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_rocker_of_dpa_groups(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 10 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_query_rocker_of_dpa_groups " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 269 "trace/trace-qapi_commands_rocker_trace_events.h"
        } else {
#line 10 "qapi/qapi-commands-rocker.trace-events"
            qemu_log("qmp_exit_query_rocker_of_dpa_groups " "%s %d" "\n", result, succeeded);
#line 273 "trace/trace-qapi_commands_rocker_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_query_rocker_of_dpa_groups(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_rocker_of_dpa_groups(result, succeeded);
    }
}
#endif /* TRACE_QAPI_COMMANDS_ROCKER_TRACE_EVENTS_GENERATED_TRACERS_H */
