/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-qapi_commands_rocker_trace_events.h"

uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE;
TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_rocker",
    .sstate = TRACE_QMP_ENTER_QUERY_ROCKER_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_ROCKER_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_rocker",
    .sstate = TRACE_QMP_EXIT_QUERY_ROCKER_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_ROCKER_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_rocker_ports",
    .sstate = TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_rocker_ports",
    .sstate = TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_rocker_of_dpa_flows",
    .sstate = TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_rocker_of_dpa_flows",
    .sstate = TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_rocker_of_dpa_groups",
    .sstate = TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_rocker_of_dpa_groups",
    .sstate = TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_DSTATE 
};
TraceEvent *qapi_commands_rocker_trace_events_trace_events[] = {
    &_TRACE_QMP_ENTER_QUERY_ROCKER_EVENT,
    &_TRACE_QMP_EXIT_QUERY_ROCKER_EVENT,
    &_TRACE_QMP_ENTER_QUERY_ROCKER_PORTS_EVENT,
    &_TRACE_QMP_EXIT_QUERY_ROCKER_PORTS_EVENT,
    &_TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_FLOWS_EVENT,
    &_TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_FLOWS_EVENT,
    &_TRACE_QMP_ENTER_QUERY_ROCKER_OF_DPA_GROUPS_EVENT,
    &_TRACE_QMP_EXIT_QUERY_ROCKER_OF_DPA_GROUPS_EVENT,
  NULL,
};

static void trace_qapi_commands_rocker_trace_events_register_events(void)
{
    trace_event_register_group(qapi_commands_rocker_trace_events_trace_events);
}
trace_init(trace_qapi_commands_rocker_trace_events_register_events)
