/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-qapi_commands_misc_target_trace_events.h"

uint16_t _TRACE_QMP_ENTER_RTC_RESET_REINJECTION_DSTATE;
uint16_t _TRACE_QMP_EXIT_RTC_RESET_REINJECTION_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_SEV_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_SEV_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_DSTATE;
uint16_t _TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_DSTATE;
uint16_t _TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_DSTATE;
uint16_t _TRACE_QMP_ENTER_DUMP_SKEYS_DSTATE;
uint16_t _TRACE_QMP_EXIT_DUMP_SKEYS_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_GIC_CAPABILITIES_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_GIC_CAPABILITIES_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_SGX_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_SGX_DSTATE;
uint16_t _TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_DSTATE;
uint16_t _TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_DSTATE;
TraceEvent _TRACE_QMP_ENTER_RTC_RESET_REINJECTION_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_rtc_reset_reinjection",
    .sstate = TRACE_QMP_ENTER_RTC_RESET_REINJECTION_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_RTC_RESET_REINJECTION_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_RTC_RESET_REINJECTION_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_rtc_reset_reinjection",
    .sstate = TRACE_QMP_EXIT_RTC_RESET_REINJECTION_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_RTC_RESET_REINJECTION_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_sev",
    .sstate = TRACE_QMP_ENTER_QUERY_SEV_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_SEV_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_sev",
    .sstate = TRACE_QMP_EXIT_QUERY_SEV_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_SEV_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_sev_launch_measure",
    .sstate = TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_sev_launch_measure",
    .sstate = TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_sev_capabilities",
    .sstate = TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_sev_capabilities",
    .sstate = TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_sev_inject_launch_secret",
    .sstate = TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_sev_inject_launch_secret",
    .sstate = TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_sev_attestation_report",
    .sstate = TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_sev_attestation_report",
    .sstate = TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_DUMP_SKEYS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_dump_skeys",
    .sstate = TRACE_QMP_ENTER_DUMP_SKEYS_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_DUMP_SKEYS_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_DUMP_SKEYS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_dump_skeys",
    .sstate = TRACE_QMP_EXIT_DUMP_SKEYS_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_DUMP_SKEYS_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_GIC_CAPABILITIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_gic_capabilities",
    .sstate = TRACE_QMP_ENTER_QUERY_GIC_CAPABILITIES_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_GIC_CAPABILITIES_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_GIC_CAPABILITIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_gic_capabilities",
    .sstate = TRACE_QMP_EXIT_QUERY_GIC_CAPABILITIES_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_GIC_CAPABILITIES_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_SGX_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_sgx",
    .sstate = TRACE_QMP_ENTER_QUERY_SGX_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_SGX_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_SGX_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_sgx",
    .sstate = TRACE_QMP_EXIT_QUERY_SGX_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_SGX_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_query_sgx_capabilities",
    .sstate = TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_query_sgx_capabilities",
    .sstate = TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_DSTATE 
};
TraceEvent *qapi_commands_misc_target_trace_events_trace_events[] = {
    &_TRACE_QMP_ENTER_RTC_RESET_REINJECTION_EVENT,
    &_TRACE_QMP_EXIT_RTC_RESET_REINJECTION_EVENT,
    &_TRACE_QMP_ENTER_QUERY_SEV_EVENT,
    &_TRACE_QMP_EXIT_QUERY_SEV_EVENT,
    &_TRACE_QMP_ENTER_QUERY_SEV_LAUNCH_MEASURE_EVENT,
    &_TRACE_QMP_EXIT_QUERY_SEV_LAUNCH_MEASURE_EVENT,
    &_TRACE_QMP_ENTER_QUERY_SEV_CAPABILITIES_EVENT,
    &_TRACE_QMP_EXIT_QUERY_SEV_CAPABILITIES_EVENT,
    &_TRACE_QMP_ENTER_SEV_INJECT_LAUNCH_SECRET_EVENT,
    &_TRACE_QMP_EXIT_SEV_INJECT_LAUNCH_SECRET_EVENT,
    &_TRACE_QMP_ENTER_QUERY_SEV_ATTESTATION_REPORT_EVENT,
    &_TRACE_QMP_EXIT_QUERY_SEV_ATTESTATION_REPORT_EVENT,
    &_TRACE_QMP_ENTER_DUMP_SKEYS_EVENT,
    &_TRACE_QMP_EXIT_DUMP_SKEYS_EVENT,
    &_TRACE_QMP_ENTER_QUERY_GIC_CAPABILITIES_EVENT,
    &_TRACE_QMP_EXIT_QUERY_GIC_CAPABILITIES_EVENT,
    &_TRACE_QMP_ENTER_QUERY_SGX_EVENT,
    &_TRACE_QMP_EXIT_QUERY_SGX_EVENT,
    &_TRACE_QMP_ENTER_QUERY_SGX_CAPABILITIES_EVENT,
    &_TRACE_QMP_EXIT_QUERY_SGX_CAPABILITIES_EVENT,
  NULL,
};

static void trace_qapi_commands_misc_target_trace_events_register_events(void)
{
    trace_event_register_group(qapi_commands_misc_target_trace_events_trace_events);
}
trace_init(trace_qapi_commands_misc_target_trace_events_register_events)
