#pragma GCC poison CONFIG_I386_DIS
#pragma GCC poison CONFIG_KVM
#pragma GCC poison CONFIG_SOFTMMU
#pragma GCC poison QEMU_ARCH
#pragma GCC poison TARGET_I386
#pragma GCC poison TARGET_NAME
#pragma GCC poison TARGET_NEED_FDT
#pragma GCC poison TARGET_SUPPORTS_MTTCG
#pragma GCC poison TARGET_X86_64
#pragma GCC poison CONFIG_AC97
#pragma GCC poison CONFIG_ACPI
#pragma GCC poison CONFIG_ACPI_CPU_HOTPLUG
#pragma GCC poison CONFIG_ACPI_ERST
#pragma GCC poison CONFIG_ACPI_HMAT
#pragma GCC poison CONFIG_ACPI_HW_REDUCED
#pragma GCC poison CONFIG_ACPI_MEMORY_HOTPLUG
#pragma GCC poison CONFIG_ACPI_NVDIMM
#pragma GCC poison CONFIG_ACPI_PCI
#pragma GCC poison CONFIG_ACPI_PCIHP
#pragma GCC poison CONFIG_ACPI_PIIX4
#pragma GCC poison CONFIG_ACPI_SMBUS
#pragma GCC poison CONFIG_ACPI_VIOT
#pragma GCC poison CONFIG_ACPI_VMGENID
#pragma GCC poison CONFIG_ACPI_X86
#pragma GCC poison CONFIG_ACPI_X86_ICH
#pragma GCC poison CONFIG_ADLIB
#pragma GCC poison CONFIG_AHCI
#pragma GCC poison CONFIG_AHCI_ICH9
#pragma GCC poison CONFIG_AMD_IOMMU
#pragma GCC poison CONFIG_APIC
#pragma GCC poison CONFIG_APM
#pragma GCC poison CONFIG_APPLESMC
#pragma GCC poison CONFIG_ATI_VGA
#pragma GCC poison CONFIG_BITBANG_I2C
#pragma GCC poison CONFIG_BOCHS_DISPLAY
#pragma GCC poison CONFIG_CAN_BUS
#pragma GCC poison CONFIG_CAN_CTUCANFD
#pragma GCC poison CONFIG_CAN_CTUCANFD_PCI
#pragma GCC poison CONFIG_CAN_PCI
#pragma GCC poison CONFIG_CAN_SJA1000
#pragma GCC poison CONFIG_CS4231A
#pragma GCC poison CONFIG_DDC
#pragma GCC poison CONFIG_DIMM
#pragma GCC poison CONFIG_E1000E_PCI_EXPRESS
#pragma GCC poison CONFIG_E1000_PCI
#pragma GCC poison CONFIG_EDID
#pragma GCC poison CONFIG_EDU
#pragma GCC poison CONFIG_EEPRO100_PCI
#pragma GCC poison CONFIG_ES1370
#pragma GCC poison CONFIG_ESP
#pragma GCC poison CONFIG_ESP_PCI
#pragma GCC poison CONFIG_FDC
#pragma GCC poison CONFIG_FDC_ISA
#pragma GCC poison CONFIG_FEMU_PCI
#pragma GCC poison CONFIG_FW_CFG_DMA
#pragma GCC poison CONFIG_GENERIC_LOADER
#pragma GCC poison CONFIG_GUEST_LOADER
#pragma GCC poison CONFIG_GUS
#pragma GCC poison CONFIG_HDA
#pragma GCC poison CONFIG_HPET
#pragma GCC poison CONFIG_HYPERV
#pragma GCC poison CONFIG_HYPERV_TESTDEV
#pragma GCC poison CONFIG_I2C
#pragma GCC poison CONFIG_I440FX
#pragma GCC poison CONFIG_I8254
#pragma GCC poison CONFIG_I8257
#pragma GCC poison CONFIG_I8259
#pragma GCC poison CONFIG_I82801B11
#pragma GCC poison CONFIG_IDE_CORE
#pragma GCC poison CONFIG_IDE_ISA
#pragma GCC poison CONFIG_IDE_PCI
#pragma GCC poison CONFIG_IDE_PIIX
#pragma GCC poison CONFIG_IDE_QDEV
#pragma GCC poison CONFIG_IMX_USBPHY
#pragma GCC poison CONFIG_IOAPIC
#pragma GCC poison CONFIG_IOH3420
#pragma GCC poison CONFIG_IPACK
#pragma GCC poison CONFIG_IPMI
#pragma GCC poison CONFIG_IPMI_EXTERN
#pragma GCC poison CONFIG_IPMI_LOCAL
#pragma GCC poison CONFIG_IPMI_SSIF
#pragma GCC poison CONFIG_ISAPC
#pragma GCC poison CONFIG_ISA_BUS
#pragma GCC poison CONFIG_ISA_DEBUG
#pragma GCC poison CONFIG_ISA_IPMI_BT
#pragma GCC poison CONFIG_ISA_IPMI_KCS
#pragma GCC poison CONFIG_ISA_TESTDEV
#pragma GCC poison CONFIG_IVSHMEM_DEVICE
#pragma GCC poison CONFIG_LPC_ICH9
#pragma GCC poison CONFIG_LSI_SCSI_PCI
#pragma GCC poison CONFIG_MC146818RTC
#pragma GCC poison CONFIG_MEGASAS_SCSI_PCI
#pragma GCC poison CONFIG_MEM_DEVICE
#pragma GCC poison CONFIG_MICROVM
#pragma GCC poison CONFIG_MPTSAS_SCSI_PCI
#pragma GCC poison CONFIG_MSI_NONBROKEN
#pragma GCC poison CONFIG_MULTIPROCESS
#pragma GCC poison CONFIG_NE2000_COMMON
#pragma GCC poison CONFIG_NE2000_ISA
#pragma GCC poison CONFIG_NE2000_PCI
#pragma GCC poison CONFIG_NMC93XX_EEPROM
#pragma GCC poison CONFIG_NVDIMM
#pragma GCC poison CONFIG_NVME_PCI
#pragma GCC poison CONFIG_PAM
#pragma GCC poison CONFIG_PARALLEL
#pragma GCC poison CONFIG_PC
#pragma GCC poison CONFIG_PCI
#pragma GCC poison CONFIG_PCIE_PORT
#pragma GCC poison CONFIG_PCI_DEVICES
#pragma GCC poison CONFIG_PCI_EXPRESS
#pragma GCC poison CONFIG_PCI_EXPRESS_GENERIC_BRIDGE
#pragma GCC poison CONFIG_PCI_EXPRESS_Q35
#pragma GCC poison CONFIG_PCI_I440FX
#pragma GCC poison CONFIG_PCI_IPMI_BT
#pragma GCC poison CONFIG_PCI_IPMI_KCS
#pragma GCC poison CONFIG_PCI_TESTDEV
#pragma GCC poison CONFIG_PCKBD
#pragma GCC poison CONFIG_PCNET_COMMON
#pragma GCC poison CONFIG_PCNET_PCI
#pragma GCC poison CONFIG_PCSPK
#pragma GCC poison CONFIG_PC_ACPI
#pragma GCC poison CONFIG_PC_PCI
#pragma GCC poison CONFIG_PFLASH_CFI01
#pragma GCC poison CONFIG_PIIX3
#pragma GCC poison CONFIG_PS2
#pragma GCC poison CONFIG_PVPANIC_COMMON
#pragma GCC poison CONFIG_PVPANIC_ISA
#pragma GCC poison CONFIG_PVPANIC_PCI
#pragma GCC poison CONFIG_PXB
#pragma GCC poison CONFIG_Q35
#pragma GCC poison CONFIG_REMOTE_PCIHOST
#pragma GCC poison CONFIG_ROCKER
#pragma GCC poison CONFIG_RTL8139_PCI
#pragma GCC poison CONFIG_SB16
#pragma GCC poison CONFIG_SCSI
#pragma GCC poison CONFIG_SD
#pragma GCC poison CONFIG_SDHCI
#pragma GCC poison CONFIG_SDHCI_PCI
#pragma GCC poison CONFIG_SERIAL
#pragma GCC poison CONFIG_SERIAL_ISA
#pragma GCC poison CONFIG_SERIAL_PCI
#pragma GCC poison CONFIG_SERIAL_PCI_MULTI
#pragma GCC poison CONFIG_SEV
#pragma GCC poison CONFIG_SGA
#pragma GCC poison CONFIG_SGX
#pragma GCC poison CONFIG_SMBIOS
#pragma GCC poison CONFIG_SMBUS
#pragma GCC poison CONFIG_SMBUS_EEPROM
#pragma GCC poison CONFIG_TEST_DEVICES
#pragma GCC poison CONFIG_TPM_BACKEND
#pragma GCC poison CONFIG_TPM_CRB
#pragma GCC poison CONFIG_TPM_EMULATOR
#pragma GCC poison CONFIG_TPM_PASSTHROUGH
#pragma GCC poison CONFIG_TPM_TIS
#pragma GCC poison CONFIG_TPM_TIS_ISA
#pragma GCC poison CONFIG_TULIP
#pragma GCC poison CONFIG_USB
#pragma GCC poison CONFIG_USB_AUDIO
#pragma GCC poison CONFIG_USB_EHCI
#pragma GCC poison CONFIG_USB_EHCI_PCI
#pragma GCC poison CONFIG_USB_NETWORK
#pragma GCC poison CONFIG_USB_OHCI
#pragma GCC poison CONFIG_USB_OHCI_PCI
#pragma GCC poison CONFIG_USB_SERIAL
#pragma GCC poison CONFIG_USB_SMARTCARD
#pragma GCC poison CONFIG_USB_STORAGE_BOT
#pragma GCC poison CONFIG_USB_STORAGE_CLASSIC
#pragma GCC poison CONFIG_USB_STORAGE_CORE
#pragma GCC poison CONFIG_USB_STORAGE_MTP
#pragma GCC poison CONFIG_USB_STORAGE_UAS
#pragma GCC poison CONFIG_USB_TABLET_WACOM
#pragma GCC poison CONFIG_USB_U2F
#pragma GCC poison CONFIG_USB_UHCI
#pragma GCC poison CONFIG_USB_XHCI
#pragma GCC poison CONFIG_USB_XHCI_NEC
#pragma GCC poison CONFIG_USB_XHCI_PCI
#pragma GCC poison CONFIG_USB_XHCI_SYSBUS
#pragma GCC poison CONFIG_VFIO
#pragma GCC poison CONFIG_VFIO_IGD
#pragma GCC poison CONFIG_VFIO_PCI
#pragma GCC poison CONFIG_VGA
#pragma GCC poison CONFIG_VGA_CIRRUS
#pragma GCC poison CONFIG_VGA_ISA
#pragma GCC poison CONFIG_VGA_PCI
#pragma GCC poison CONFIG_VHOST
#pragma GCC poison CONFIG_VHOST_USER_BLK
#pragma GCC poison CONFIG_VHOST_USER_GPU
#pragma GCC poison CONFIG_VHOST_USER_I2C
#pragma GCC poison CONFIG_VHOST_USER_INPUT
#pragma GCC poison CONFIG_VHOST_USER_RNG
#pragma GCC poison CONFIG_VHOST_USER_SCSI
#pragma GCC poison CONFIG_VHOST_USER_VGA
#pragma GCC poison CONFIG_VIRTIO
#pragma GCC poison CONFIG_VIRTIO_BALLOON
#pragma GCC poison CONFIG_VIRTIO_BLK
#pragma GCC poison CONFIG_VIRTIO_CRYPTO
#pragma GCC poison CONFIG_VIRTIO_GPU
#pragma GCC poison CONFIG_VIRTIO_INPUT
#pragma GCC poison CONFIG_VIRTIO_INPUT_HOST
#pragma GCC poison CONFIG_VIRTIO_IOMMU
#pragma GCC poison CONFIG_VIRTIO_MEM
#pragma GCC poison CONFIG_VIRTIO_MEM_SUPPORTED
#pragma GCC poison CONFIG_VIRTIO_MMIO
#pragma GCC poison CONFIG_VIRTIO_NET
#pragma GCC poison CONFIG_VIRTIO_PCI
#pragma GCC poison CONFIG_VIRTIO_PMEM
#pragma GCC poison CONFIG_VIRTIO_PMEM_SUPPORTED
#pragma GCC poison CONFIG_VIRTIO_RNG
#pragma GCC poison CONFIG_VIRTIO_SCSI
#pragma GCC poison CONFIG_VIRTIO_SERIAL
#pragma GCC poison CONFIG_VIRTIO_VGA
#pragma GCC poison CONFIG_VMBUS
#pragma GCC poison CONFIG_VMMOUSE
#pragma GCC poison CONFIG_VMPORT
#pragma GCC poison CONFIG_VMWARE_VGA
#pragma GCC poison CONFIG_VMW_PVSCSI_SCSI_PCI
#pragma GCC poison CONFIG_VMXNET3_PCI
#pragma GCC poison CONFIG_VTD
#pragma GCC poison CONFIG_WDT_IB6300ESB
#pragma GCC poison CONFIG_WDT_IB700
#pragma GCC poison CONFIG_X86_FW_OVMF
#pragma GCC poison CONFIG_X86_IOMMU
#pragma GCC poison CONFIG_XIO3130
